"use client";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "../lib/supabase";

export function AccountManagement({forceAllowed=true,defaultRole,title="Tài khoản đăng nhập"}:{forceAllowed?:boolean;defaultRole?:"teacher"|"student";title?:string}){
 const[allowed,setAllowed]=useState(forceAllowed),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{if(forceAllowed||!supabase)return;(async()=>{const{data}=await supabase.auth.getUser();if(!data.user)return;const{data:p}=await supabase.from("profiles").select("role").eq("id",data.user.id).single();setAllowed(p?.role==="admin")})()},[forceAllowed]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setMsg("");const form=new FormData(e.currentTarget);const{data}=await supabase.auth.getSession();const res=await fetch("/.netlify/functions/admin-users",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session?.access_token||""}`},body:JSON.stringify({username:form.get("username"),password:form.get("password"),full_name:form.get("full_name"),role:defaultRole||form.get("role")})});const body=await res.json();setBusy(false);if(!res.ok)return setMsg(body.error||"Không thể tạo tài khoản.");setMsg(`Đã tạo tài khoản ${body.username}.`);e.currentTarget.reset()}
 if(!allowed)return null;
 return <section className="panel account-admin"><div className="panel-head"><div><h3>{title}</h3><p>Admin tạo username và mật khẩu; dữ liệu được lưu trên Supabase.</p></div><button className="primary" onClick={()=>setOpen(!open)}>{open?"Đóng":"Tạo tài khoản"}</button></div>{open&&<form className="account-form" onSubmit={submit}><label>Họ và tên<input name="full_name" required/></label>{defaultRole?<input type="hidden" name="role" value={defaultRole}/>:<label>Vai trò<select name="role"><option value="teacher">Giáo viên</option><option value="student">Học viên</option></select></label>}<label>Username<input name="username" required minLength={3} pattern="[a-zA-Z0-9._-]+" autoCapitalize="none"/></label><label>Password<input name="password" type="password" required minLength={8}/></label><button className="primary" disabled={busy}>{busy?"Đang tạo…":"Lưu tài khoản"}</button></form>}{msg&&<p className="account-message">{msg}</p>}</section>
}
