"use client";
import {useEffect,useMemo,useState} from "react";
import {BookOpen,CalendarDays,UserCheck} from "lucide-react";
import {supabase} from "../lib/supabase";
import {ClassManagement} from "./classes-view-v2";

type ClassRow={id:string;code:string;name:string;room?:string;status:string};
type Session={id:string;class_id:string;session_no:number;session_date:string;start_time:string;end_time:string;status:string;classes?:{code:string;name:string;room?:string}|null};
type Person={id:string;full_name:string;student_code?:string;username:string};
const fmt=(d:string)=>new Intl.DateTimeFormat("vi-VN",{day:"2-digit",month:"2-digit"}).format(new Date(`${d}T12:00:00`));
const money=(n:number)=>new Intl.NumberFormat("vi-VN",{style:"currency",currency:"VND",maximumFractionDigits:0}).format(n);

function useCenterData(){const[classes,setClasses]=useState<ClassRow[]>([]),[students,setStudents]=useState<Person[]>([]),[teachers,setTeachers]=useState<Person[]>([]),[sessions,setSessions]=useState<Session[]>([]),[members,setMembers]=useState<{class_id:string;student_id:string}[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");async function load(){if(!supabase){setError("Supabase chưa được cấu hình.");setLoading(false);return}setLoading(true);const today=new Date(),from=new Date(today);from.setDate(today.getDate()-today.getDay()+1);const to=new Date(from);to.setDate(from.getDate()+41);const iso=(x:Date)=>x.toISOString().slice(0,10);const [c,p,t,s,m]=await Promise.all([supabase.from("classes").select("id,code,name,room,status").order("code"),supabase.from("profiles").select("id,full_name,student_code,username").eq("role","student").order("full_name"),supabase.from("profiles").select("id,full_name,username").eq("role","teacher").order("full_name"),supabase.from("class_sessions").select("id,class_id,session_no,session_date,start_time,end_time,status,classes(code,name,room)").gte("session_date",iso(from)).lte("session_date",iso(to)).order("session_date"),supabase.from("class_members").select("class_id,student_id")]);const e=c.error||p.error||t.error||s.error||m.error;if(e)setError(e.message);else{setClasses((c.data||[]) as ClassRow[]);setStudents((p.data||[]) as Person[]);setTeachers((t.data||[]) as Person[]);setSessions((s.data||[]) as unknown as Session[]);setMembers((m.data||[]) as {class_id:string;student_id:string}[])}setLoading(false)}useEffect(()=>{void load()},[]);return{classes,students,teachers,sessions,members,loading,error,load}}

function Calendar({sessions}:{sessions:Session[]}){const[mode,setMode]=useState<"week"|"month">("week");const start=useMemo(()=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-d.getDay()+1);return d},[]);const days=mode==="week"?7:35;return <><div className="calendar-toolbar"><div className="view-toggle"><button className={mode==="week"?"active":""} onClick={()=>setMode("week")}>Tuần</button><button className={mode==="month"?"active":""} onClick={()=>setMode("month")}>Tháng</button></div></div><div className={mode==="week"?"visual-week":"visual-month"}>{Array.from({length:days},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().slice(0,10),items=sessions.filter(x=>x.session_date===key);return <article className={items.length?"has-event":""} key={key}><header><b>{mode==="week"?`T${d.getDay()+1}`:d.getDate()}</b><span>{fmt(key)}</span></header>{items.map(x=><div className="visual-event" key={x.id}><b>{x.classes?.code||"Lớp"}</b><span>{x.start_time?.slice(0,5)} • {x.classes?.room||"Chưa xếp phòng"}</span></div>)}</article>})}</div></>}

export function AdminOverviewDb(){const d=useCenterData();if(d.loading)return <section className="panel">Đang tải số liệu Supabase…</section>;return <>{d.error&&<p className="live-error">{d.error}</p>}<section className="admin-kpis"><article><span>Học viên đã từng học</span><strong>{d.students.length}</strong><small>Theo hồ sơ học viên trên Supabase</small></article><article><span>Học viên hiện tại</span><strong>{d.students.length}</strong><small>{d.members.length} lượt ghi danh lớp</small></article><article><span>Số lớp</span><strong>{d.classes.length}</strong><small>{d.classes.filter(x=>x.status==="active").length} lớp đang hoạt động</small></article></section><section className="panel"><div className="panel-head"><div><h3>Lịch học của trung tâm</h3><p>Dữ liệu trực tiếp từ class_sessions</p></div></div><Calendar sessions={d.sessions}/></section></>}

export function CenterCalendarDb(){const d=useCenterData();return <>{d.error&&<p className="live-error">{d.error}</p>}{d.loading?<section className="panel">Đang tải lịch Supabase…</section>:<Calendar sessions={d.sessions}/>}</>}

export function AdminClassHubDb(){const d=useCenterData(),[tab,setTab]=useState<"list"|"calendar"|"attendance">("list"),[classId,setClassId]=useState("");useEffect(()=>{if(!classId&&d.classes[0])setClassId(d.classes[0].id)},[d.classes,classId]);const roster=d.students.filter(s=>d.members.some(m=>m.class_id===classId&&m.student_id===s.id));return <div className="admin-class-hub"><div className="class-tabs"><button className={tab==="list"?"active":""} onClick={()=>setTab("list")}><BookOpen/>Danh sách lớp</button><button className={tab==="calendar"?"active":""} onClick={()=>setTab("calendar")}><CalendarDays/>Lịch trung tâm</button><button className={tab==="attendance"?"active":""} onClick={()=>setTab("attendance")}><UserCheck/>Điểm danh</button></div>{tab==="list"&&<><ClassManagement/><section className="panel"><h3>Học viên theo lớp</h3><select className="wide-select" value={classId} onChange={e=>setClassId(e.target.value)}>{d.classes.map(c=><option value={c.id} key={c.id}>{c.code} • {c.name}</option>)}</select><div className="compact-students">{roster.length?roster.map(s=><span key={s.id}><b>{s.full_name}</b><small>{s.student_code||s.username}</small></span>):<p>Chưa có học viên được gán vào lớp này.</p>}</div></section></>}{tab==="calendar"&&<Calendar sessions={d.sessions}/>} {tab==="attendance"&&<AttendanceDb data={d}/>}</div>}

function AttendanceDb({data}:{data:ReturnType<typeof useCenterData>}){const[classId,setClassId]=useState(""),[sessionId,setSessionId]=useState(""),[status,setStatus]=useState<Record<string,string>>({}),[message,setMessage]=useState("");useEffect(()=>{if(!classId&&data.classes[0])setClassId(data.classes[0].id)},[data.classes,classId]);const sessions=data.sessions.filter(s=>s.class_id===classId),roster=data.students.filter(s=>data.members.some(m=>m.class_id===classId&&m.student_id===s.id));useEffect(()=>{if(sessions[0]&&!sessions.some(s=>s.id===sessionId))setSessionId(sessions[0].id)},[classId,sessions,sessionId]);useEffect(()=>{if(!supabase||!sessionId)return;supabase.from("attendance").select("student_id,status").eq("session_id",sessionId).then(({data})=>setStatus(Object.fromEntries((data||[]).map(x=>[x.student_id,x.status]))))},[sessionId]);async function save(){if(!supabase||!sessionId)return;const{data:u}=await supabase.auth.getUser();const rows=roster.filter(s=>status[s.id]).map(s=>({session_id:sessionId,student_id:s.id,status:status[s.id],marked_by:u.user?.id}));const{error}=rows.length?await supabase.from("attendance").upsert(rows,{onConflict:"session_id,student_id"}):{error:null};setMessage(error?error.message:"Đã lưu điểm danh vào Supabase.")}return <><div className="attendance-controls"><select value={classId} onChange={e=>setClassId(e.target.value)}>{data.classes.map(c=><option value={c.id} key={c.id}>{c.code} • {c.name}</option>)}</select><select value={sessionId} onChange={e=>setSessionId(e.target.value)}>{sessions.map(s=><option value={s.id} key={s.id}>{fmt(s.session_date)} • Buổi {s.session_no}</option>)}</select><button className="primary" onClick={save}>Lưu điểm danh</button></div><section className="panel attendance-v14">{roster.map(s=><article key={s.id}><span><b>{s.full_name}</b><small>{s.student_code||s.username}</small></span><div>{[["present","Có mặt"],["excused","Vắng phép"],["unexcused","Vắng"]].map(x=><button key={x[0]} className={status[s.id]===x[0]?"selected":""} onClick={()=>setStatus({...status,[s.id]:x[0]})}>{x[1]}</button>)}</div></article>)}</section>{message&&<p className="auto-note">{message}</p>}</>}

export function TuitionDb(){const[students,setStudents]=useState<Person[]>([]),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{if(!supabase)return;Promise.all([supabase.from("profiles").select("id,full_name,student_code,username").eq("role","student"),supabase.from("tuition_records").select("id,student_id,amount,paid_amount,status,due_date,classes(code)")]).then(([p,t])=>{setStudents((p.data||[]) as Person[]);setRows(t.data||[]);setLoading(false)})},[]);const total=rows.reduce((n,r)=>n+Number(r.amount||0),0),paid=rows.reduce((n,r)=>n+Number(r.paid_amount||0),0);const list=[...students].sort((a,b)=>{const sa=rows.find(r=>r.student_id===a.id)?.status||"pending",sb=rows.find(r=>r.student_id===b.id)?.status||"pending";return sa==="paid"?1:sb==="paid"?-1:0});if(loading)return <section className="panel">Đang tải học phí Supabase…</section>;return <><div className="section-head"><div><h2>Quản lý học phí</h2><p>Số liệu được tổng hợp trực tiếp từ tuition_records.</p></div></div><section className="tuition-dashboard"><article><h3>Tổng hợp học phí</h3><div className="fee-donut"><span>{total?Math.round(paid/total*100):0}%</span></div><ul><li><i className="paid"/>Đã thu: {money(paid)}</li><li><i className="pending"/>Còn phải thu: {money(Math.max(0,total-paid))}</li></ul></article></section><section className="panel student-manage-list"><div className="student-manage-row head"><span>Học viên</span><span>Lớp</span><span>Số tiền</span><span>Tình trạng</span><span/></div>{list.map(s=>{const r=rows.find(x=>x.student_id===s.id),st=r?.status||"pending";return <div className={`student-manage-row ${st!=="paid"?"fee-alert":""}`} key={s.id}><span><b>{s.full_name}</b><small>{s.student_code||s.username}</small></span><span>{r?.classes?.code||"Chưa gán"}</span><span>{money(Number(r?.amount||0))}</span><span><mark className={st!=="paid"?"warning":""}>{st==="paid"?"Đã nộp":st==="partial"?"Nộp một phần":st==="overdue"?"Quá hạn":"Chưa nộp"}</mark></span><span/></div>})}</section></>}
