"use client";
import {useState} from "react";
import {BookOpen,CalendarDays,CheckCircle2,Clock3,Pencil,Plus,UserCheck,Users,WalletCards,X} from "lucide-react";
import {ClassManagement} from "./classes-view-v2";

const classes=["I67-A • IELTS 6.5","IF-C • IELTS Foundation","J4-B • Junior 4","COM-A • Communication"];
const students=[
 {name:"Nguyễn Minh Anh",code:"IPA-24031",classes:["I67-A","IF-C"],login:"minhanh",attendance:96,fee:"Đã nộp",score:"8.2"},
 {name:"Trần Gia Huy",code:"IPA-24044",classes:["J4-B"],login:"",attendance:89,fee:"Chưa nộp",score:"7.4"},
 {name:"Lê Khánh Linh",code:"IPA-24052",classes:["IF-C"],login:"khanhlinh",attendance:93,fee:"Đã nộp",score:"8.8"},
 {name:"Phạm Đức Minh",code:"IPA-24063",classes:["COM-A"],login:"",attendance:82,fee:"Quá hạn",score:"6.9"}
];
const teachers=[
 {name:"Cô Mai Anh",phone:"090 123 4567",email:"maianh@ipa.edu.vn",classes:["I67-A","IF-C"],login:"mai.anh"},
 {name:"Thầy David",phone:"091 225 8899",email:"david@ipa.edu.vn",classes:["J4-B"],login:"david.nguyen"},
 {name:"Cô Ngọc Anh",phone:"098 556 7711",email:"ngocanh@ipa.edu.vn",classes:["COM-A"],login:""}
];
const schedule=[
 {day:"T2",date:"14/09",items:[["IF-C","20:00","Forest"]]},
 {day:"T3",date:"15/09",items:[["I67-A","18:00","Ocean"],["COM-A","20:00","River"]]},
 {day:"T4",date:"16/09",items:[["J4-B","17:30","Sky"]]},
 {day:"T5",date:"17/09",items:[["I67-A","18:00","Ocean"]]},
 {day:"T6",date:"18/09",items:[["IF-C","20:00","Forest"]]},
 {day:"T7",date:"19/09",items:[["J4-B","17:30","Sky"]]}
];

export function AdminOverviewV14(){return <><section className="admin-kpis"><article><span>Học viên đã từng học</span><strong>1.284</strong><small>Từ khi thành lập trung tâm</small></article><article><span>Học viên hiện tại</span><strong>248</strong><small>12 học viên mới tháng này</small></article><article><span>Số lớp</span><strong>18</strong><small>15 lớp đang hoạt động</small></article></section><section className="panel"><div className="panel-head"><div><h3>Lịch học tuần của trung tâm</h3><p>14/09–20/09/2026</p></div></div><WeekCalendar/></section></>}

export function AdminClassHub(){const[tab,setTab]=useState<"list"|"calendar"|"attendance">("list");return <div className="admin-class-hub"><div className="section-head"><div><h2>Quản lý lớp học</h2><p>Danh sách lớp, lịch trung tâm và điểm danh.</p></div></div><div className="class-tabs"><button className={tab==="list"?"active":""} onClick={()=>setTab("list")}><BookOpen/>Danh sách lớp</button><button className={tab==="calendar"?"active":""} onClick={()=>setTab("calendar")}><CalendarDays/>Lịch trung tâm</button><button className={tab==="attendance"?"active":""} onClick={()=>setTab("attendance")}><UserCheck/>Điểm danh</button></div>{tab==="list"&&<div className="class-pane"><ClassManagement/><section className="panel"><h3>Học viên theo lớp</h3><select className="wide-select">{classes.map(c=><option key={c}>{c}</option>)}</select><div className="compact-students">{students.filter(s=>s.classes.includes("I67-A")).map(s=><span key={s.code}><b>{s.name}</b><small>{s.code} • {s.attendance}% chuyên cần</small></span>)}</div></section></div>}{tab==="calendar"&&<CenterCalendarV14/>}{tab==="attendance"&&<AttendanceV14/>}</div>}

export function CenterCalendarV14(){const[mode,setMode]=useState<"week"|"month">("week"),[edit,setEdit]=useState(false);return <><div className="calendar-toolbar"><div className="view-toggle"><button className={mode==="week"?"active":""} onClick={()=>setMode("week")}>Tuần</button><button className={mode==="month"?"active":""} onClick={()=>setMode("month")}>Tháng</button></div><button className="secondary" onClick={()=>setEdit(true)}><Pencil/>Thay đổi lịch học</button></div>{mode==="week"?<WeekCalendar/>:<MonthCalendar/>}{edit&&<SessionEdit close={()=>setEdit(false)}/>}</>}

function WeekCalendar(){return <div className="visual-week">{schedule.map(d=><article key={d.date}><header><b>{d.day}</b><span>{d.date}</span></header>{d.items.map(i=><div className="visual-event" key={i[0]+i[1]}><b>{i[0]}</b><span>{i[1]} • {i[2]}</span></div>)}</article>)}</div>}
function MonthCalendar(){return <div className="visual-month">{Array.from({length:30},(_,i)=>i+1).map(d=><article className={[3,5,8,10,12,15,17,19,22,24,26,29].includes(d)?"has-event":""} key={d}><b>{d}</b>{[3,10,17,24].includes(d)&&<span>I67-A • 18:00</span>}{[5,12,19,26].includes(d)&&<span>IF-C • 20:00</span>}</article>)}</div>}

function SessionEdit({close}:{close:()=>void}){const[status,setStatus]=useState("reschedule");return <div className="modal-layer"><button className="modal-backdrop" onClick={close}/><div className="modal"><div className="modal-head"><div><span><CalendarDays/></span><h2>Thay đổi lịch học</h2></div><button onClick={close}><X/></button></div><div className="form-grid"><label className="full">Buổi học<select><option>I67-A • 17/09 • 18:00–19:30</option><option>IF-C • 18/09 • 20:00–21:30</option></select></label><label>Trạng thái<select value={status} onChange={e=>setStatus(e.target.value)}><option value="reschedule">Đổi lịch</option><option value="cancel">Cho nghỉ</option></select></label><label>Lý do<input placeholder="Nhập lý do thay đổi"/></label>{status==="reschedule"&&<><label>Ngày mới<input type="date" defaultValue="2026-09-20"/></label><label>Giờ mới<input type="time" defaultValue="18:00"/></label></>}{status==="cancel"&&<label className="full">Phương án<select><option>Tạo buổi học bù mới</option><option>Nghỉ và không học bù</option></select></label>}</div><div className="modal-actions"><button className="secondary" onClick={close}>Hủy</button><button className="primary" onClick={close}>Lưu thay đổi</button></div></div></div>}

function AttendanceV14(){const[status,setStatus]=useState<Record<string,string>>({"IPA-24031":"present","IPA-24044":"excused","IPA-24052":"present","IPA-24063":"absent"});return <><div className="attendance-controls"><select>{classes.map(c=><option key={c}>{c}</option>)}</select><select><option>17/09/2026 • Buổi 25</option><option>15/09/2026 • Buổi 24</option></select><button className="primary">Lưu điểm danh</button></div><section className="panel attendance-v14">{students.map(s=><article key={s.code}><span><b>{s.name}</b><small>{s.code}{s.code==="IPA-24044"&&" • Đã xin nghỉ"}</small></span><div>{[["present","Có mặt"],["excused","Vắng phép"],["absent","Vắng"]].map(x=><button key={x[0]} className={status[s.code]===x[0]?"selected":""} onClick={()=>setStatus({...status,[s.code]:x[0]})}>{x[1]}</button>)}</div></article>)}</section><p className="auto-note">Đơn xin nghỉ được học viên gửi và duyệt sẽ tự động chuyển sang “Vắng phép”.</p></>}

export function StudentManagementV14(){const[filter,setFilter]=useState("all"),[selected,setSelected]=useState<typeof students[0]|null>(null),[editing,setEditing]=useState<typeof students[0]|null|undefined>(undefined);const list=filter==="all"?students:students.filter(s=>s.classes.includes(filter));return <><div className="section-head"><div><h2>Quản lý học viên</h2><p>Hồ sơ, lớp học, tài khoản, học phí và kết quả học tập.</p></div><button className="primary" onClick={()=>setEditing(null)}><Plus/>Thêm học viên</button></div><div className="filter-line"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Toàn bộ học viên</option>{classes.map(c=><option key={c} value={c.split(" ")[0]}>{c}</option>)}</select></div><section className="panel student-manage-list"><div className="student-manage-row head"><span>Học viên</span><span>Lớp đang học</span><span>Tài khoản</span><span>Chuyên cần</span><span/></div>{list.map(s=><div className="student-manage-row" key={s.code} onClick={()=>setSelected(s)}><span><b>{s.name}</b><small>{s.code}</small></span><span>{s.classes.join(", ")}</span><span className={!s.login?"missing":""}>{s.login||"Chưa có"}</span><span>{s.attendance}%</span><button className="secondary compact" onClick={e=>{e.stopPropagation();setEditing(s)}}><Pencil/> Edit</button></div>)}</section>{selected&&<StudentDetail data={selected} close={()=>setSelected(null)}/>} {editing!==undefined&&<StudentEditor data={editing} close={()=>setEditing(undefined)}/>}</>}

function StudentDetail({data,close}:{data:typeof students[0];close:()=>void}){return <div className="modal-layer"><button className="modal-backdrop" onClick={close}/><div className="modal detail-modal"><div className="modal-head"><div><span><Users/></span><h2>{data.name}</h2></div><button onClick={close}><X/></button></div><div className="detail-grid"><article><small>Thông tin chung</small><b>{data.code}</b><span>Lớp: {data.classes.join(", ")}</span><span>Tài khoản: {data.login||"Chưa cấp"}</span></article><article><small>Tình trạng học phí</small><b>{data.fee}</b><span>Học phí kỳ hiện tại</span></article><article><small>Báo cáo học tập</small><b>Điểm TB {data.score}</b><span>Chuyên cần {data.attendance}%</span></article></div></div></div>}

function StudentEditor({data,close}:{data:typeof students[0]|null;close:()=>void}){return <div className="modal-layer"><button className="modal-backdrop" onClick={close}/><form className="modal" onSubmit={e=>{e.preventDefault();close()}}><div className="modal-head"><div><span><Users/></span><h2>{data?"Chỉnh sửa học viên":"Thêm học viên"}</h2></div><button type="button" onClick={close}><X/></button></div><div className="form-grid"><label>Họ và tên<input required defaultValue={data?.name}/></label><label>Ngày sinh<input type="date"/></label><label>Số điện thoại<input/></label><label>Điện thoại phụ huynh<input/></label><label className="full">Địa chỉ<input/></label><fieldset className="full"><legend>Gán lớp học — có thể chọn nhiều lớp</legend>{classes.map(c=><label className="check-line" key={c}><input type="checkbox" defaultChecked={data?.classes.includes(c.split(" ")[0])}/>{c}</label>)}</fieldset><label>Username<input required={!data?.login} defaultValue={data?.login}/></label><label>Password<input type="password" required={!data?.login} placeholder={data?.login?"Để trống nếu không đổi":"Tối thiểu 8 ký tự"}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Hủy</button><button className="primary">Lưu học viên</button></div></form></div>}

export function TuitionV14(){const[scope,setScope]=useState("all"),[period,setPeriod]=useState("month");const sorted=[...students].sort((a,b)=>(a.fee==="Đã nộp"?1:0)-(b.fee==="Đã nộp"?1:0));return <><div className="section-head"><div><h2>Quản lý học phí</h2><p>Ưu tiên học viên chưa nộp và báo cáo theo thời gian.</p></div></div><div className="tuition-filters"><select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">Toàn trung tâm</option>{classes.map(c=><option key={c}>{c}</option>)}</select><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="month">Theo tháng</option><option value="quarter">Theo quý</option><option value="year">Theo năm</option></select></div><section className="tuition-dashboard"><article><h3>Tổng hợp học phí</h3><div className="fee-donut"><span>78%</span></div><ul><li><i className="paid"/>Đã thu: 428 triệu</li><li><i className="pending"/>Chưa thu: 82 triệu</li><li><i className="overdue"/>Quá hạn: 24 triệu</li></ul></article><article><h3>Xu hướng thu học phí</h3><div className="fee-bars">{[62,78,70,88,82,94].map((v,i)=><span key={i} style={{height:`${v}%`}}><b>{v}</b></span>)}</div></article></section><section className="panel student-manage-list"><div className="student-manage-row head"><span>Học viên</span><span>Lớp</span><span>Số tiền</span><span>Tình trạng</span><span/></div>{sorted.map((s,i)=><div className={`student-manage-row ${s.fee!=="Đã nộp"?"fee-alert":""}`} key={s.code}><span><b>{s.name}</b><small>{s.code}</small></span><span>{s.classes.join(", ")}</span><span>{["12.500.000đ","9.500.000đ","18.000.000đ","18.000.000đ"][i]}</span><span><mark className={s.fee!=="Đã nộp"?"warning":""}>{s.fee}</mark></span><button className="secondary compact">Cập nhật</button></div>)}</section></>}

export function StaffV14(){const[edit,setEdit]=useState<typeof teachers[0]|null|undefined>(undefined);return <><div className="section-head"><div><h2>Quản lý nhân sự</h2><p>Hồ sơ, lớp được phân công và tài khoản Giáo viên.</p></div><button className="primary" onClick={()=>setEdit(null)}><Plus/>Bổ sung giáo viên</button></div><section className="panel student-manage-list"><div className="student-manage-row head"><span>Giáo viên</span><span>Liên hệ</span><span>Lớp phụ trách</span><span>Tài khoản</span><span/></div>{teachers.map(t=><div className="student-manage-row" key={t.email}><span><b>{t.name}</b><small>{t.email}</small></span><span>{t.phone}</span><span>{t.classes.join(", ")}</span><span className={!t.login?"missing":""}>{t.login||"Chưa có"}</span><button className="secondary compact" onClick={()=>setEdit(t)}><Pencil/> Edit</button></div>)}</section>{edit!==undefined&&<TeacherEditor data={edit} close={()=>setEdit(undefined)}/>}</>}

function TeacherEditor({data,close}:{data:typeof teachers[0]|null;close:()=>void}){return <div className="modal-layer"><button className="modal-backdrop" onClick={close}/><form className="modal" onSubmit={e=>{e.preventDefault();close()}}><div className="modal-head"><div><span><Users/></span><h2>{data?"Chỉnh sửa giáo viên":"Bổ sung giáo viên"}</h2></div><button type="button" onClick={close}><X/></button></div><div className="form-grid"><label>Họ và tên<input required defaultValue={data?.name}/></label><label>Ngày sinh<input type="date"/></label><label>Số điện thoại<input defaultValue={data?.phone}/></label><label>Email<input type="email" defaultValue={data?.email}/></label><label className="full">Địa chỉ<input/></label><fieldset className="full"><legend>Phân công lớp</legend>{classes.map(c=><label className="check-line" key={c}><input type="checkbox" defaultChecked={data?.classes.includes(c.split(" ")[0])}/>{c}</label>)}</fieldset><label>Username<input required={!data?.login} defaultValue={data?.login}/></label><label>Password<input type="password" required={!data?.login} placeholder={data?.login?"Để trống nếu không đổi":"Tối thiểu 8 ký tự"}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Hủy</button><button className="primary">Lưu giáo viên</button></div></form></div>}
