"use client";
import {useState} from "react";
import {BarChart3, BookOpen, CalendarDays, CheckCircle2, ClipboardCheck, Clock3, FileText, Link2, MessageSquare, Plus, Upload, UserRound, Users, WalletCards} from "lucide-react";
import {AccountManagement} from "./account-management";

const people=[
 {name:"Cô Mai Anh",user:"mai.anh",classes:"I67-A, IF-C",phone:"090 123 4567",status:"Đang giảng dạy"},
 {name:"Thầy David",user:"david.nguyen",classes:"J4-B",phone:"091 225 8899",status:"Đang giảng dạy"},
 {name:"Cô Ngọc Anh",user:"ngoc.anh",classes:"COM-A",phone:"098 556 7711",status:"Đang giảng dạy"}
];
const pupils=[
 {name:"Nguyễn Minh Anh",code:"IPA-24031",attendance:"96%",tuition:"Đã hoàn thành",score:"8.2"},
 {name:"Trần Gia Huy",code:"IPA-24044",attendance:"89%",tuition:"Còn 1 kỳ",score:"7.4"},
 {name:"Lê Khánh Linh",code:"IPA-24052",attendance:"93%",tuition:"Đã hoàn thành",score:"8.8"},
 {name:"Phạm Đức Minh",code:"IPA-24063",attendance:"82%",tuition:"Quá hạn",score:"6.9"}
];

export function CenterCalendar(){const[mode,setMode]=useState<"week"|"month">("week");const days=mode==="week"?["T2 14/09","T3 15/09","T4 16/09","T5 17/09","T6 18/09","T7 19/09"]:["01–06","07–13","14–20","21–27","28–30"];return <><div className="section-head"><div><h2>Lịch toàn trung tâm</h2><p>Xem lịch lớp theo tuần hoặc tháng.</p></div><div className="view-toggle"><button className={mode==="week"?"active":""} onClick={()=>setMode("week")}>Tuần</button><button className={mode==="month"?"active":""} onClick={()=>setMode("month")}>Tháng</button></div></div><section className={`center-calendar ${mode}`}>{days.map((d,i)=><article key={d}><strong>{d}</strong><div className="calendar-event blue"><b>{["I67-A","IF-C","J4-B","COM-A"][i%4]}</b><span>{i%2?"18:00–19:30":"20:00–21:30"}</span><small>{["Ocean","Forest","Sky"][i%3]} • {["Cô Mai Anh","Thầy David"][i%2]}</small></div>{mode==="month"&&i<3&&<div className="calendar-event green"><b>J4-B</b><span>17:30–19:00</span></div>}</article>)}</section></>}

export function StaffManagement(){return <><AccountManagement forceAllowed defaultRole="teacher" title="Cấp tài khoản giáo viên"/><div className="section-head"><div><h2>Quản lý nhân sự</h2><p>Hồ sơ, tài khoản và phân công lớp cho giáo viên.</p></div><button className="primary"><Plus/> Bổ sung giáo viên</button></div><section className="panel data-list"><div className="data-row data-head"><span>Giáo viên</span><span>Tài khoản</span><span>Lớp phụ trách</span><span>Liên hệ</span><span>Trạng thái</span></div>{people.map(p=><div className="data-row" key={p.user}><span><b>{p.name}</b><small>Giáo viên tiếng Anh</small></span><span>{p.user}</span><span>{p.classes}</span><span>{p.phone}</span><span><mark>{p.status}</mark></span></div>)}</section></>}

export function TuitionManagement(){return <><div className="section-head"><div><h2>Theo dõi học phí</h2><p>Đối soát tình trạng học phí theo học viên và khóa học.</p></div><button className="secondary"><FileText/> Xuất báo cáo</button></div><section className="stat-grid"><MiniStat icon={WalletCards} label="Đã thu tháng này" value="428 triệu"/><MiniStat icon={CheckCircle2} label="Đã hoàn thành" value="216"/><MiniStat icon={Clock3} label="Sắp đến hạn" value="24"/><MiniStat icon={MessageSquare} label="Quá hạn" value="8"/></section><section className="panel data-list"><div className="data-row data-head"><span>Học viên</span><span>Khóa học</span><span>Học phí</span><span>Hạn thanh toán</span><span>Tình trạng</span></div>{pupils.map((p,i)=><div className="data-row" key={p.code}><span><b>{p.name}</b><small>{p.code}</small></span><span>IELTS 6.5 • I67-A</span><span>{["18.000.000đ","12.500.000đ","18.000.000đ","9.500.000đ"][i]}</span><span>{["Hoàn tất","25/09/2026","Hoàn tất","10/09/2026"][i]}</span><span><mark className={p.tuition==="Quá hạn"?"warning":""}>{p.tuition}</mark></span></div>)}</section></>}

export function TeacherClasses(){return <><div className="section-head"><div><h2>Lớp được phân công</h2><p>Giáo viên chỉ truy cập các lớp do Admin phân công.</p></div></div><div className="feature-cards">{[["I67-A","IELTS 6.5","18 học viên","T3, T5 • 18:00"],["IF-C","IELTS Foundation","16 học viên","T2, T6 • 20:00"]].map(c=><article className="feature-card" key={c[0]}><span className="code-pill">{c[0]}</span><h3>{c[1]}</h3><p>{c[2]} • {c[3]}</p><div><button className="secondary">Danh sách lớp</button><button className="secondary">Lịch học</button></div></article>)}</div></>}

export function TeacherAttendance(){return <><div className="section-head"><div><h2>Điểm danh lớp</h2><p>I67-A • Buổi 25/36 • 18/09/2026</p></div><button className="primary">Lưu điểm danh</button></div><section className="panel attendance-list">{pupils.map((p,i)=><article key={p.code}><span><b>{p.name}</b><small>{p.code} • Chuyên cần {p.attendance}</small></span><div><button className={i!==3?"selected":""}>Có mặt</button><button>Vắng phép</button><button className={i===3?"danger selected":""}>Vắng</button></div></article>)}</section></>}

export function TeacherAssignments({grading=false}:{grading?:boolean}){if(grading)return <Grading/>;return <><div className="section-head"><div><h2>Giao bài tập</h2><p>Giao cho cả lớp hoặc riêng từng học viên.</p></div><button className="primary"><Plus/> Giao bài mới</button></div><section className="panel assignment-builder"><div className="form-grid"><label>Đối tượng<select><option>Cả lớp I67-A</option><option>Học viên cụ thể</option></select></label><label>Học viên<select><option>— Tất cả học viên —</option><option>Nguyễn Minh Anh</option><option>Trần Gia Huy</option></select></label><label className="full">Tên bài tập<input placeholder="Ví dụ: Speaking — Describe a journey"/></label><label>Hạn nộp<input type="datetime-local"/></label><label>Định dạng<select><option>Text</option><option>Link</option><option>Ảnh / Video</option><option>Kết hợp</option></select></label><label className="full">Nội dung<textarea rows={4} placeholder="Hướng dẫn và yêu cầu bài tập..."/></label><label className="full upload-inline"><Upload/> Đính kèm ảnh/video<input type="file" accept="image/*,video/*"/></label></div><button className="primary">Giao bài tập</button></section><AssignmentQueue/></>}

function Grading(){return <><div className="section-head"><div><h2>Chấm bài và phản hồi</h2><p>Chấm điểm, comment và gửi nhắc nhở riêng.</p></div></div><section className="panel grading-list">{pupils.slice(0,3).map((p,i)=><article key={p.code}><div><b>{p.name}</b><small>Writing Task 2 • Nộp {17+i}/09</small></div><span className="submission-types"><FileText/> Text <Link2/> Link</span><input type="number" min="0" max="10" step="0.5" defaultValue={8-i*.5}/><textarea placeholder="Nhận xét cho học viên..." defaultValue={i===0?"Bố cục tốt, cần cải thiện phần kết luận.":""}/><div><button className="secondary"><MessageSquare/> Nhắc riêng</button><button className="primary">Lưu điểm</button></div></article>)}</section></>}

function AssignmentQueue(){return <section className="panel"><h3>Bài tập đang theo dõi</h3>{["Writing Task 2 — Education","Speaking recording","Vocabulary review"].map((x,i)=><div className="simple-line" key={x}><span><b>{x}</b><small>{i?"Giao cả lớp":"Giao riêng Nguyễn Minh Anh"}</small></span><span>{14-i*2}/{18-i*2} đã nộp</span><mark>{i===2?"Chờ chấm":"Đang mở"}</mark></div>)}</section>}

export function LearningReports({teacher=false}:{teacher?:boolean}){return <><div className="section-head"><div><h2>{teacher?"Báo cáo lớp và học viên":"Báo cáo học tập"}</h2><p>Tiến độ, chuyên cần, bài tập và nhận xét.</p></div><button className="secondary"><FileText/> Xuất báo cáo</button></div><section className="report-choice"><button className="active"><Users/> Theo lớp</button><button><UserRound/> Theo học viên</button></section><section className="panel data-list"><div className="data-row data-head"><span>Học viên</span><span>Chuyên cần</span><span>Hoàn thành bài</span><span>Điểm TB</span><span>Xu hướng</span></div>{pupils.map(p=><div className="data-row" key={p.code}><span><b>{p.name}</b><small>{p.code}</small></span><span>{p.attendance}</span><span>86%</span><span>{p.score}</span><span className="trend">↗ Tiến bộ</span></div>)}</section></>}

export function StudentCourse(){return <><div className="section-head"><div><h2>Khóa học của tôi</h2><p>Thông tin, học phí và lịch trình khóa học.</p></div></div><section className="course-summary"><article><BookOpen/><span><small>Khóa học</small><b>IELTS 6.5 • I67-A</b><em>24/36 buổi đã hoàn thành</em></span></article><article><WalletCards/><span><small>Tình trạng học phí</small><b>Đã hoàn thành</b><em>18.000.000đ • 12/08/2026</em></span></article><article><CalendarDays/><span><small>Lịch học</small><b>T3, T5 • 18:00–19:30</b><em>Phòng Ocean • Cô Mai Anh</em></span></article></section><section className="panel"><h3>Lịch trình sắp tới</h3>{["22/09 • Writing — Task response","24/09 • Speaking — Part 2","29/09 • Mock test"].map((x,i)=><div className="simple-line" key={x}><span><b>{x}</b><small>{i===2?"Kiểm tra định kỳ":"Buổi học bình thường"}</small></span><mark>{i===0?"Sắp tới":"Đã lên lịch"}</mark></div>)}</section></>}

function MiniStat({icon:Icon,label,value}:{icon:typeof Users,label:string,value:string}){return <article className="stat-card"><div className="stat-icon blue"><Icon/></div><div><span>{label}</span><strong>{value}</strong></div></article>}
