"use client";
import { BarChart3, BookOpen, CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, Clock3, Plus, TrendingUp, Users } from "lucide-react";

export type AccountRole = "admin" | "teacher" | "student";

export function LoginScreen({ onLogin }: { onLogin: (role: AccountRole) => void }) {
  const accounts = [
    { role: "admin" as AccountRole, title: "Quản trị viên", name: "IPA Admin", email: "admin@ipaenglish.com", icon: "AD", note: "Toàn quyền quản lý hệ thống" },
    { role: "teacher" as AccountRole, title: "Giáo viên", name: "Cô Mai Anh", email: "teacher@ipaenglish.com", icon: "GV", note: "Lớp học, bài tập và chấm bài" },
    { role: "student" as AccountRole, title: "Học viên", name: "Nguyễn Minh Anh", email: "student@ipaenglish.com", icon: "HV", note: "Bài tập, tiến độ và xin nghỉ" }
  ];
  return <main className="login-page"><section className="login-brand"><img src="/ipa-logo.jpg" alt="IPA English Academy"/><span>IPA ENGLISH ACADEMY</span><h1>Mỗi hành trình học tập<br/>đều xứng đáng được theo sát.</h1><p>Student HUB kết nối học viện, giáo viên và học viên trên một không gian thống nhất.</p></section><section className="login-panel"><div className="login-box"><span className="eyebrow">STUDENT HUB</span><h2>Đăng nhập tài khoản</h2><p>Chọn tài khoản mẫu để trải nghiệm đúng giao diện được phân quyền.</p><div className="account-list">{accounts.map(a => <button key={a.role} onClick={() => onLogin(a.role)}><i>{a.icon}</i><span><strong>{a.title} — {a.name}</strong><small>{a.email}</small><em>{a.note}</em></span><ChevronRight/></button>)}</div><small className="demo-note">Mật khẩu demo: <b>IPA@2026</b> • Bản production sẽ xác thực qua Supabase.</small></div></section></main>;
}

function TeacherStat({ icon: Icon, label, value, note, tone }: { icon: typeof Users; label: string; value: string; note: string; tone: string }) {
  return <article className="stat-card"><div className={`stat-icon ${tone}`}><Icon/></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>;
}

export function TeacherOverview({ onNew, go }: { onNew: () => void; go: (view: "assignments" | "reports") => void }) {
  return <><section className="welcome-banner teacher-banner"><div><span>GIÁO VIÊN • CÔ MAI ANH</span><h2>3 lớp học cần bạn theo dõi</h2><p>Hôm nay có 2 tiết dạy và 16 bài nộp mới cần phản hồi.</p></div><button className="primary" onClick={onNew}><Plus/> Giao bài tập</button></section><section className="stat-grid"><TeacherStat icon={Users} label="Học viên phụ trách" value="48" note="3 lớp đang học" tone="blue"/><TeacherStat icon={CalendarDays} label="Tiết dạy tuần này" value="8" note="2 tiết hôm nay" tone="green"/><TeacherStat icon={ClipboardCheck} label="Bài cần chấm" value="16" note="5 bài nộp mới" tone="orange"/><TeacherStat icon={TrendingUp} label="Điểm TB lớp" value="7.6" note="+0.3 tháng này" tone="purple"/></section><section className="dashboard-grid"><div className="panel"><div className="panel-title"><div><h3>Bài nộp cần chấm</h3><p>Sắp xếp theo hạn phản hồi</p></div><button onClick={() => go("assignments")}>Mở danh sách <ChevronRight/></button></div><div className="teacher-submissions"><button><i>MA</i><span><strong>Writing Task 2 — Nguyễn Minh Anh</strong><small>Nộp 14/09 • Chưa chấm</small></span><b>Chấm bài</b></button><button><i>GH</i><span><strong>Speaking Recording — Trần Gia Huy</strong><small>Nộp 13/09 • Chưa chấm</small></span><b>Chấm bài</b></button><button><i>KL</i><span><strong>Vocabulary Review — Lê Khánh Linh</strong><small>Nộp 13/09 • Đang chấm</small></span><b>Tiếp tục</b></button></div></div><div className="panel"><div className="panel-title"><div><h3>Lịch dạy hôm nay</h3><p>Thứ Hai, 14/09</p></div></div><div className="schedule"><div className="date-box"><b>18</b><span>GIỜ</span></div><div><strong>IELTS Writing • I67-A</strong><p>Phòng Ocean • 18 học viên</p></div></div><div className="schedule"><div className="date-box"><b>20</b><span>GIỜ</span></div><div><strong>IELTS Foundation • IF-C</strong><p>Phòng Forest • 16 học viên</p></div></div></div></section><section className="panel"><div className="panel-title"><div><h3>Tiến độ lớp phụ trách</h3><p>Dựa trên chuyên cần và kết quả bài tập</p></div><button onClick={() => go("reports")}>Đánh giá chi tiết <ChevronRight/></button></div><div className="class-progress"><article><BookOpen/><span><strong>IELTS 6.5 • I67-A</strong><small>18 học viên • Chuyên cần 96%</small></span><progress value="82" max="100"/><b>8.2</b></article><article><BarChart3/><span><strong>IELTS Foundation • IF-C</strong><small>16 học viên • Chuyên cần 93%</small></span><progress value="76" max="100"/><b>7.6</b></article><article><CheckCircle2/><span><strong>Junior 4 • J4-B</strong><small>14 học viên • Chuyên cần 89%</small></span><progress value="74" max="100"/><b>7.4</b></article></div></section></>;
}
